### ISSUE TITLE
[BUG]Meta rule for protecting routes is not working since latest update

### ISSUE THREAD

**Issue by jsinhSolanki** [leonardovilarinho/vue-acl#64]
Hello,
I have live project with acl implemented which have route protection feature. But recently I installed this package in same project with same code. But route protection is not working.
Please check as soon as possible.
~ Regards

**Comment by leonardovilarinho** [comment]
Hello,

What version did you use before? From version 3 to 4 the plugin was rewritten and a new way of using it was created, this may be what is happening.

For without any descriptive maneuver of error I can not know.

**Comment by jsinhSolanki** [comment]
Hi @leonardovilarinho, I have used 4.0.7 which is workiing fine. Recently I updated this to 4.1.0 and route protection is not working.
When i downgrade vue-acl to 4.0.7 it worked.
Hope you will fix this soon.
~ Thanks

**Comment by ymoreiratiti** [comment]
Same problem here.

I downgrade and work like a charm

**Comment by leonardovilarinho** [comment]
Fixed b9e96f0f6bdadc060d8ea18030dbb95634084091

**Comment by jsinhSolanki** [comment]
Hello @leonardovilarinho 
Thanks for your hard work. But this issue is still not solved I am using **vue-acl@4.1.5**.
Can you please confirm this?

~ Regards

**Comment by ymoreiratiti** [comment]
Same here.

Tried vue-acl@4.15 and using this on Quasar Framework.

vue-acl.js
```javascript
import { AclInstaller, AclCreate, AclRule } from 'vue-acl'

// leave the export, even if you don't use it
export default ({ app, router, Vue }) => {
  Vue.use(AclInstaller)
  const aclcreate = new AclCreate({
    initial: 'unauthenticated',
    notfound: '/Login',
    router,
    acceptLocalRules: true,
    globalRules: {
      isAdmin: new AclRule('admin').generate(),
      isUnauthenticated: new AclRule('unauthenticated').generate(),
      isAuthenticated: new AclRule('authenticated').generate(),
      isEveryone: new AclRule('authenticated').or('unauthenticated').generate()
    }
  })

  Vue.use(aclcreate)
}
```

route.js
```javascript
{
    path: '/Dashboard',
    component: () => import('layouts/Dashboard.vue'),
    meta: { rule: 'isAuthenticated' }
  }
```

**Comment by jd-0001** [comment]
@leonardovilarinho we are still facing this issue any update on this. please re-open this issue.

**Comment by danijelh** [comment]
Also can confirm this, does not work on the vue-acl@4.15.

Downgraded to vue-acl@4.0.7.
